# Generated by Django 2.2.4 on 2021-03-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0004_add_object_pk_is_removed_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sf_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
